// Auto-generated by scripts/build_nav.py — do not edit by hand.
// Source: ~/dev/leurenmoret/index.html nav tree.

export interface NavItem {
  href: string | null
  label: string
  children?: NavItem[]
  current?: boolean
}

export const NAV_ITEMS: NavItem[] = [
    { href: null, label: "❁ Home", current: true },
    { href: "/currents", label: "❁ Currents", children: [
        { href: "/currents/uc-davis-katehi-illuminati", label: "🎥 UC, Davis, Katehi, Illuminati ✠", children: [
            { href: "/currents/uc-davis-katehi-illuminati/radchick-ucdavis-transcript", label: "⚛ RadChick: UCDavis Transcript 📜" },
            { href: "/currents/uc-davis-katehi-illuminati/illustrations-uc-davis", label: "🎨 Illustrations, UC, Davis, Katehi, Illuminati ✠" }
          ] },
        { href: "/currents/exotic-weapons-geopolitics/programmable-rna-", label: "💉 Programmable RNA 🙈🙉🙊" },
        { href: "/currents/exotic-weapons-geopolitics/dna-ram-01", label: "✏️ DNA RAM 0️⃣1️⃣" },
        { href: "/currents/one-world-religion", label: "🌎✟☦ One World Religion 🎭" },
        { href: "/currents/atlanticists-v-putin-et-al-", label: "♞ Atlanticists v. Putin et al ⚪️" },
        { href: "/currents/3-nwo-false-flags-connected", label: "✈️ 3 NWO False Flags Connected ➷" },
        { href: "/currents/ukrainian-wikileaks-intervi", label: "🔪Ukrainian ✠ Wikileaks 👀 Interview 🎥" },
        { href: "/currents/out-of-eurasia-", label: "🚫 Out of Eurasia 🚫" },
        { href: "/currents/jade-helm-international", label: "💀 Jade Helm, International Implications, NWO Rollouts ⏰" },
        { href: "/currents/essential-oils-nutrition", label: "🌿 Essential Oils, Nutrition, Frequencies & Health 🌺" },
        { href: "/currents/rfde--haarp--nlp-", label: "🎯 R.F.D.E. | H.A.A.R.P. | N.L.P. ⚡️" },
        { href: "/currents/leuren-moret-hiroshima", label: "⚛ Leuren Moret: Hiroshima, Nagasaki, Fukushima ⚛" },
        { href: "/currents/moret--battis-jade-helm-", label: "❦ Moret & Battis: Jade Helm ❦" },
        { href: "/currents/new-world-order-america-", label: "🌎 New World Order America 🇺🇸" },
        { href: "/currents/geopolitics-ukraine--eu", label: "⨳ Geopolitics Ukraine | E.U. Judo 🌍" },
        { href: "/currents/template-jade-helm", label: "👥 Template: Jade Helm" },
        { href: "/currents/americas-domestic-pacificat", label: "✠ America’s Domestic Pacification ✠" },
        { href: "/currents/chernobyl-zaporozhye-blackm", label: "♨️ Chernobyl, Zaporozhye, Blackmail ⚛" },
        { href: "/currents/rebranding-disaster", label: "💉 REBRANDING DISASTER🔪" },
        { href: "/currents/eurasian-enigma-arises", label: "👤 Eurasian Enigma Arises" },
        { href: "/currents/donetsk-nuclear-explosion", label: "🔴 Donetsk Nuclear Explosion ⚫️", children: [
            { href: "/currents/donetsk-nuclear-explosion/interview--donetsk-nuclear", label: "🎥 Interview 🔴 Donetsk Nuclear Attack ⚫️" },
            { href: "/currents/donetsk-nuclear-explosion/absolutely-massive-nuke", label: "⛔️ ”Absolutely Massive,\" Nuke Explosion Ukraine" }
          ] },
        { href: "/currents/21st-century-silk-road", label: "🌍 21st Century Silk Road 🌏", children: [
            { href: "/currents/21st-century-silk-road/silk-road-strategies-", label: "🌍 Silk Road Strategies 🌐" },
            { href: "/currents/21st-century-silk-road/21st-century-silk-road-pt1-", label: "🌍 21st Century Silk Road PT1 🌏" },
            { href: "/currents/21st-century-silk-road/21st-century-silk-road-pt2-", label: "🌍 21st Century Silk Road PT2 🌏" },
            { href: "/currents/21st-century-silk-road/21st-century-silk-road-pt3-", label: "🌍 21st Century Silk Road PT3 🌏" }
          ] },
        { href: "/currents/africa", label: "🌍 Africa ☗", children: [
            { href: "/currents/africa/libyas-orwellian-bienvenue-", label: "🇫🇷 Libya's Orwellian Bienvenue 💣" }
          ] },
        { href: "/currents/the-nameless-triangle", label: "♞ Balkans, The Nameless Triangle", children: [
            { href: "/currents/the-nameless-triangle/verdict-first--sentences", label: "📜 VERDICT FIRST | SENTENCES LATER ♨️" },
            { href: "/currents/the-nameless-triangle/macedonian-uprising--wester", label: "⏰💀 Macedonian Uprising / Western NGO's" },
            { href: "/currents/the-nameless-triangle/minsk-nyet-boisto-island", label: "⏰ Minsk? Nyet! Boisto Island" },
            { href: "/currents/the-nameless-triangle/and-now-the-flawed-minsk", label: "☞ ☜ And Now the Flawed Minsk Agreement" }
          ] },
        { href: "/currents/china", label: "🌏 China 🌝", children: [
            { href: "/currents/china/300-years-wasted-", label: "➷ 300 Years Wasted 💀" }
          ] },
        { href: "/currents/eurasia", label: "🌍 Eurasia 🔴", children: [
            { href: "/currents/eurasia/oil-money--eu-laundromat-", label: "💰 Oil Money? | EU Laundromat? 🚿" },
            { href: "/currents/eurasia/terrorist-christmas-jihadi", label: "💣 Terrorist Christmas, Jihadi New Year 💀" },
            { href: "/currents/eurasia/stable-oil-trade-", label: "🌞 Stable Oil Trade 🌝" }
          ] },
        { href: "/currents/israel-out-of-erupt", label: "💣 Israel: Out of Erupt!", children: [
            { href: "/currents/israel-out-of-erupt/israel-forced-to-investigat", label: "💀 Israel Forced to Investigate ☚" },
            { href: "/currents/israel-out-of-erupt/sweden-a-stage-is-set", label: "🎈 Sweden: A Stage is Set" }
          ] },
        { href: "/currents/jesuitstemplars-origins", label: "✠ Jesuits/Templar’s Origins & Aims", children: [
            { href: "/currents/jesuitstemplars-origins/soros-nwo-hacked", label: "👺 SOROS ✠ NWO 📚 Hacked ✍" },
            { href: "/currents/jesuitstemplars-origins/pyatts-soros-breakfast", label: "➴ Pyatt’s ✠ SOROS ♞ Breakfast 🍳" },
            { href: "/currents/jesuitstemplars-origins/breedlove-good-riddance", label: "Breedlove, GOOD RIDDANCE" },
            { href: "/currents/jesuitstemplars-origins/obamas-3-billion-eurocon-", label: "🎱 Obama’s $3 Billion Eurocon 💸" },
            { href: "/currents/jesuitstemplars-origins/a-psychopaths-psychopath-", label: "🌍 A Psychopath’s Psychopath ✠" },
            { href: "/currents/jesuitstemplars-origins/global-hit-squad-", label: "🔫 Global Hit Squad 💣" },
            { href: "/currents/jesuitstemplars-origins/neo-capitalists-slave-trade", label: "💀 Neo-Capitalist’s Slave Trade 💰", children: [
                { href: "/currents/jesuitstemplars-origins/neo-capitalists-slave-trade/terrorist-law-on-slaves-", label: "💰 Terrorist Law on Slaves 💀" },
                { href: "/currents/jesuitstemplars-origins/neo-capitalists-slave-trade/be-somebody-be-a-minion-", label: "💩 Be Somebody, Be A Minion! 💩" }
              ] },
            { href: "/currents/jesuitstemplars-origins/bio-undermine-control", label: "🇺🇸 Bio: Undermine Control" },
            { href: "/currents/jesuitstemplars-origins/fine-evening-for-a-minuet-", label: "↷ Fine Evening For A Minuet ↶" },
            { href: "/currents/jesuitstemplars-origins/slavery-then--now", label: "✠ Slavery, Then & Now" },
            { href: "/currents/jesuitstemplars-origins/jcs-operation-northwoods", label: "💣 JCS Operation Northwoods" },
            { href: "/currents/jesuitstemplars-origins/the-three-secret-meetings", label: "✠ The Three Secret Meetings" }
          ] },
        { href: "/currents/korea-yeonhee-nuclear-kabuk", label: "Korea Yeonhee (연희) Nuclear Kabuki Theatre" },
        { href: "/currents/middle-east", label: "🌍 Middle East 💣", children: [
            { href: "/currents/middle-east/smashing-turkeys-game", label: "☞ Smashing Turkey’s Game❌" },
            { href: "/currents/middle-east/juncker-eu-direction", label: "🌍 Juncker | E.U. | Direction ⤣" }
          ] },
        { href: "/currents/north-america", label: "🌎 North America 🔥✠", children: [
            { href: "/currents/north-america/alberta-oil-sands-fire-", label: "🌎🔥 Alberta Oil Sands Fire 🌎🔥" }
          ] },
        { href: "/currents/russia-is-coming", label: "🇷🇺 Russia 🇷🇺", children: [
            { href: "/currents/russia-is-coming/putin-overhauls-kremlin-", label: "🇷🇺 PUTIN OVERHAULS KREMLIN 🏰" },
            { href: "/currents/russia-is-coming/who-created-isis", label: "☛ Who Created ISIS ☚", children: [
                { href: "/currents/russia-is-coming/who-created-isis/assads-isis-interview-", label: "☞ Assad’s ISIS Interview 🎥" }
              ] },
            { href: "/currents/russia-is-coming/food-supply-compromised-", label: "🍳 Food Supply Compromised 🎱" },
            { href: "/currents/russia-is-coming/putin-re-ceasefire-syria-", label: "🌍 Putin re Ceasefire Syria 🌐" },
            { href: "/currents/russia-is-coming/cold-war-re-run-", label: "👤 Cold War Re-Run 👀" },
            { href: "/currents/russia-is-coming/minsk101-theatre-of-absurd", label: "🌐 Minsk 101 | Theatre of the Absurd 🌍" },
            { href: "/currents/russia-is-coming/geopolitical-original-sin-", label: "🌐 Geopolitical Original Sin 🌍" },
            { href: "/currents/russia-is-coming/russian-troops--turkish", label: "♘ Russian Troops | Turkish Border ♘" },
            { href: "/currents/russia-is-coming/educating-charlie-rose", label: "📚 Educating Charlie Rose 🔑" },
            { href: "/currents/russia-is-coming/lavrovs-munich-speech", label: "🌍 Lavrov's Munich Speech" },
            { href: "/currents/russia-is-coming/us-embassy-media-fail-", label: "🎱 US Embassy Media Fail 🎭" },
            { href: "/currents/russia-is-coming/putins-jar-of-spiders", label: "✠ ♛🃏 Putin’s Jar Of Spiders" },
            { href: "/currents/russia-is-coming/mossads-on-the-doorstep-", label: "🎱 MOSSAD’S ON THE DOORSTEP 💣" },
            { href: "/currents/russia-is-coming/this-document-is-dynamite-", label: "📄 This Document is Dynamite 📄" },
            { href: "/currents/russia-is-coming/the-golden-trap", label: "♔ The Golden Trap" },
            { href: "/currents/russia-is-coming/russian-fusion-fission", label: "❁ Russian Fusion-Fission" },
            { href: "/currents/russia-is-coming/putins-7-point-plan", label: "❁ Putin’s 7-Point Plan" },
            { href: "/currents/russia-is-coming/russian-position-speech", label: "❁ Russian Position Speech" }
          ] },
        { href: "/currents/mh-17-jesuits-flagged-brics", label: "✈︎ Ukraine, MH-17, Jesuits Flagged! BRICS Undermined?", children: [
            { href: "/currents/mh-17-jesuits-flagged-brics/ukraine-bail-out", label: "⏰ Ukraine? 🔥 Bail Out! ✈️", children: [
                { href: "/currents/mh-17-jesuits-flagged-brics/ukraine-bail-out/poroshenko-calls-merkel-", label: "🐟 Poroshenko Calls Merkel 🐙" },
                { href: "/currents/mh-17-jesuits-flagged-brics/ukraine-bail-out/poroshenkos-spanish-villa-", label: "🃏 Poroshenko’s Spanish Villa 🏰" }
              ] },
            { href: "/currents/mh-17-jesuits-flagged-brics/psychotropic-zombification", label: "💦👤 Psychotropic Zombification ☔️" },
            { href: "/currents/mh-17-jesuits-flagged-brics/odessa-trade-union-murders-", label: "💣 Odessa Trade Union Murders 🔥" },
            { href: "/currents/mh-17-jesuits-flagged-brics/nothing-personal-just-busin", label: "🃏 Nothing Personal, Just Business 💰" },
            { href: "/currents/mh-17-jesuits-flagged-brics/bioweapons-for-depopulation", label: "💉 BioWeapons for Depopulation 💀" },
            { href: "/currents/mh-17-jesuits-flagged-brics/nuclear-coverup-ukraine-", label: "⚛ Nuclear Coverup Ukraine | Mines of Zholti Vody 💀" },
            { href: "/currents/mh-17-jesuits-flagged-brics/unsustainable-ukraine-", label: "🔥 Unsustainable Ukraine 👥" },
            { href: "/currents/mh-17-jesuits-flagged-brics/ashes-to-ashes-", label: "☗ ASHES TO ASHES 💀" },
            { href: "/currents/mh-17-jesuits-flagged-brics/ukrainian-wikileaks-", label: "🔪Ukrainian Wikileaks 👀" },
            { href: "/currents/mh-17-jesuits-flagged-brics/dispatches-from-the-front-", label: "☞ Dispatches From the Front 🔫" },
            { href: "/currents/mh-17-jesuits-flagged-brics/the-ukrainian-failed-state", label: "💣 The Ukrainian Failed State 🌍" },
            { href: "/currents/mh-17-jesuits-flagged-brics/our-decisions-define-us", label: "🔑 Our Decisions Define Us🔑" },
            { href: "/currents/mh-17-jesuits-flagged-brics/child-abuse", label: "✠ Child Abuse 💀", children: [
                { href: "/currents/mh-17-jesuits-flagged-brics/child-abuse/ukronazi-abc", label: "✏️ UkroNazi ABC’s 📕" }
              ] },
            { href: "/currents/mh-17-jesuits-flagged-brics/mozgovois-murder", label: "💣 Mozgovoi’s Murder 🔪" },
            { href: "/currents/mh-17-jesuits-flagged-brics/yatsenyuks-russian-threat-", label: "🎱 Yatsenyuk's Russian Threat 🔮" },
            { href: "/currents/mh-17-jesuits-flagged-brics/prison-ukraine-", label: "||| Prison Ukraine |||" },
            { href: "/currents/mh-17-jesuits-flagged-brics/cyberberkut-reports", label: "✍ CyberBerkut Reports 👥", children: [
                { href: "/currents/mh-17-jesuits-flagged-brics/cyberberkut-reports/usnukraine-caught-red-hande", label: "💀 U.S.’n’Ukraine Caught Red Handed ☜", children: [
                    { href: "/currents/mh-17-jesuits-flagged-brics/cyberberkut-reports/usnukraine-caught-red-hande/caught-red-handed--cyberber", label: "☞ Caught Red Handed ☜ CyberBerkut Original" }
                  ] },
                { href: "/currents/mh-17-jesuits-flagged-brics/cyberberkut-reports/soros-letters-ukraine", label: "📄 Soros Letters | Ukraine ✠", children: [
                    { href: "/currents/mh-17-jesuits-flagged-brics/cyberberkut-reports/soros-letters-ukraine/soros-draft-non-paper-", label: "⚇ SOROS Draft Non-Paper ⚇" }
                  ] }
              ] },
            { href: "/currents/mh-17-jesuits-flagged-brics/crazy-arseniys--used--ukrai", label: "♨️ Crazy Arseniy’s -USED- Ukraine Fire Sale! ♨️" },
            { href: "/currents/mh-17-jesuits-flagged-brics/azov-crucifixion-", label: "✝ AZOV CRUCIFIXION ✝" },
            { href: "/currents/mh-17-jesuits-flagged-brics/eyewitness-debaltsevo-cauld", label: "👤 Eyewitness Debaltsevo Cauldron 💀" },
            { href: "/currents/mh-17-jesuits-flagged-brics/historic-slaviansk-doctor", label: "✍ Historic Slaviansk Doctor Interviewed" },
            { href: "/currents/mh-17-jesuits-flagged-brics/the-tragedy-of-uglegorsk", label: "💀 The Tragedy of Uglegorsk" },
            { href: "/currents/mh-17-jesuits-flagged-brics/jan-2015-minsk-fail-", label: "♟ Jan. 2015 Minsk Fail 🃏" },
            { href: "/currents/mh-17-jesuits-flagged-brics/tochka-found-debaltsevo", label: "➷ Tochka Found, Debaltsevo Locked" },
            { href: "/currents/mh-17-jesuits-flagged-brics/world-facing-second-chernob", label: "🌍 World Facing Second Chernobyl" },
            { href: "/currents/mh-17-jesuits-flagged-brics/mh-17-and-the-jesuit-minuet", label: "✈︎ MH-17 AND THE Jesuit Minuet" },
            { href: "/currents/mh-17-jesuits-flagged-brics/mh-17-jesuits-flagged-video", label: "✈︎ MH-17, Jesuits Flagged!, Video" },
            { href: "/currents/mh-17-jesuits-flagged-brics/deaths-drummers", label: "💀 Death’s Drummers" },
            { href: "/currents/mh-17-jesuits-flagged-brics/dpr-novorossiya-calling", label: "👤 DPR! Novorossiya Calling" },
            { href: "/currents/mh-17-jesuits-flagged-brics/ukraines-chernobyl-armor", label: "💀 Ukraine’s Chernobyl Armor" },
            { href: "/currents/mh-17-jesuits-flagged-brics/gas-to-ukraine-blocked", label: "🎱 Gas to Ukraine Blocked" },
            { href: "/currents/mh-17-jesuits-flagged-brics/global-nuclear-theatre", label: "❁ Global Nuclear Theatre: Donbass" },
            { href: "/currents/mh-17-jesuits-flagged-brics/ghosts-of-the-51st-brigade", label: "✠ GHOSTS of the 51st BRIGADE" },
            { href: "/currents/mh-17-jesuits-flagged-brics/novorossiya-strelkov-briefi", label: "❁ Novorossiya: Strelkov Briefing" },
            { href: "/currents/mh-17-jesuits-flagged-brics/open-letter-to-president", label: "👤 Open Letter to President Putin" },
            { href: "/currents/mh-17-jesuits-flagged-brics/mh-17-dutch-interim-report", label: "✈︎ MH-17 Dutch Interim Report" },
            { href: "/currents/mh-17-jesuits-flagged-brics/surrendering-ua-murdered-by", label: "💣 Surrendering UA Murdered by Punatives" },
            { href: "/currents/mh-17-jesuits-flagged-brics/mutiny-of-the-euro-integrat", label: "♟ Mutiny of the Euro-Integrators ♟" },
            { href: "/currents/mh-17-jesuits-flagged-brics/view-from-ukraine-operating", label: "➹ View from Ukraine Operating Room" },
            { href: "/currents/mh-17-jesuits-flagged-brics/ukraines-violent-escalation", label: "❁ Ukraine’s Violent Escalation" },
            { href: "/currents/mh-17-jesuits-flagged-brics/ukrainian-soldiers-cry-for", label: "❁ Ukrainian Soldier’s Cry for Help" },
            { href: "/currents/mh-17-jesuits-flagged-brics/occupied-ukraine-", label: "⧱ Occupied Ukraine ⧱" },
            { href: "/currents/mh-17-jesuits-flagged-brics/us-states-nuland-directs", label: "❁ US State's Nuland Directs Ukrainian Coup" },
            { href: "/currents/mh-17-jesuits-flagged-brics/ukraine-deputies-knew-befor", label: "📯 Ukraine Deputies Knew Before Maidan" }
          ] },
        { href: "/currents/health-in-2015", label: "❁ Health In 2015" },
        { href: "/currents/vaccines-", label: "💉 Vaccines 💀" },
        { href: "/currents/geopolitics-jesuits--histor", label: "🎥 Geopolitics, Jesuits & History" },
        { href: "/currents/rebranded--the-jesuits-", label: "🎥 Rebranded ✠ The Jesuits ✠" },
        { href: "/currents/zaporhyze-nuclear-events-", label: "⚛ Zaporhyze Nuclear Events & Geopolitics" },
        { href: "/currents/fukushima-polar-vortex", label: "❁ Fukushima Polar Vortex Radiation ❁" },
        { href: "/currents/embrace-enfold-extinguish", label: "💀 Embrace, Enfold, Extinguish" },
        { href: "/currents/fear-of-flying-1of4", label: "✈︎ Fear of Flying . . . (1of4)", children: [
            { href: "/currents/fear-of-flying-1of4/fear-of-flying-2of4", label: "✈︎ Fear of Flying . . . 2of4" },
            { href: "/currents/fear-of-flying-1of4/fear-of-flying-3", label: "✈︎ Fear of Flying 3" },
            { href: "/currents/fear-of-flying-1of4/fear-of-flying-4", label: "✈︎ Fear of Flying 4" }
          ] },
        { href: "/currents/fukushima-impact-of-fallout", label: "❁ Fukushima: Impact of Fallout On Oceans (Pt.1)" },
        { href: "/currents/fukushima-impact-of-fallout-2", label: "❁ Fukushima: Impact of Fallout On Oceans (Pt. 2)" },
        { href: "/currents/north-america-middle-east", label: "❁ North America, Middle East and Fukushima" },
        { href: "/currents/dhsnapolitano-berkeley", label: "❁ DHS/Napolitano Berkeley Template" },
        { href: "/currents/fukushima-radiation-ecocide", label: "❁ Fukushima Radiation, Ecocide & Tesla Technology" },
        { href: "/currents/flight-370-downing", label: "⚛ Flight 370 Downing" },
        { href: "/currents/mh370-the-follow-up", label: "✈︎ MH370: The Follow-Up" },
        { href: "/currents/domestic-radiation-issues", label: "❁ Domestic Radiation Issues" },
        { href: "/currents/fukushima-hawaii-pacific-is", label: "❁ Fukushima: Hawaii, Pacific Is. - Unsafe" },
        { href: "/currents/fukushima-reactors-breakdow", label: "⚛ Fukushima Reactors, Breakdown 1-6 ⚛" },
        { href: "/currents/international-sites-featuri", label: "🌏 International Sites Featuring LM:GNC" },
        { href: "/currents/on-to-mongolia-", label: "❁ On To Mongolia 🎥" },
        { href: "/currents/lkm-on-fairdinkum-assets/images", label: "🎥 LKM On Fairdinkum Media 🎥", children: [
            { href: "/currents/lkm-on-fairdinkum-assets/images/the-jesuits-in-geopolitics", label: "✠ The Jesuits in Geopolitics" }
          ] },
        { href: "/currents/editorial-page", label: "❁ Editorial Page", children: [
            { href: "/currents/editorial-page/april-fooles-2016-", label: "🎉April Fooles! 2016 🙊" },
            { href: "/currents/editorial-page/yatsenyuks-failed-state", label: "Yatsenyuk’s Failed-State Cookbook" },
            { href: "/currents/editorial-page/haarp-season-", label: "⚑ H.A.A.R.P. Season ⚑" },
            { href: "/currents/editorial-page/psyop-101", label: "↵ Psyop 101 ⟲", children: [
                { href: "/currents/editorial-page/psyop-101/doc-1-stratcom-training.pdf", label: "Doc 1. stratcom-training.pdf" },
                { href: "/currents/editorial-page/psyop-101/doc-2-conflict-pool-project.pdf", label: "Doc 2. conflict-pool-project.pdf" },
                { href: "/currents/editorial-page/psyop-101/doc-3-free-donbass.pdf", label: "Doc 3. free-donbass.pdf" },
                { href: "/currents/editorial-page/psyop-101/doc-4-free-russiappsxppsx.pdf", label: "Doc 4. free-russia(ppsx).ppsx.pdf" }
              ] },
            { href: "/currents/editorial-page/r2p-the-nwo", label: "⨳ R2P THE NWO ⨳" },
            { href: "/currents/editorial-page/tbilisi-2008-ukraine-today", label: "➷ Tbilisi 2008, Ukraine Today" },
            { href: "/currents/editorial-page/the-old-new-endless-war", label: "✠ The Old, New, Endless War" },
            { href: "/currents/editorial-page/a-new-maidan-awaits", label: "✠ A New \"Maidan\" Awaits" },
            { href: "/currents/editorial-page/your-federal-appropriations", label: "❁ Your Federal Appropriations Scams at Work" },
            { href: "/currents/editorial-page/amusements", label: "🎈Amusements 🎭" }
          ] },
        { href: "/currents/conversations", label: "❁ Conversations 📬", children: [
            { href: "/currents/conversations/uranium-mine-on-tribal-land", label: "⇊⇊ Uranium Mine on Tribal Land ⚛⚛⚛" },
            { href: "/currents/conversations/re-geiger-counters-", label: "📬 re: Geiger Counters ⚛⚛⚛" },
            { href: "/currents/conversations/cybercom-suppression-silo-", label: "⚡️CYBERCOM Suppression Silo 🎯" },
            { href: "/currents/conversations/pacific-coast-watch", label: "🌎 Pacific Coast Watch" },
            { href: "/currents/conversations/cruel-murder-of-boris-nemts", label: "♟ Cruel Murder of Boris Nemtsov", children: [
                { href: "/currents/conversations/cruel-murder-of-boris-nemts/more-re-nemtsov-murder", label: "⚔ More re: Nemtsov Murder" },
                { href: "/currents/conversations/cruel-murder-of-boris-nemts/a-decoy-for-murder", label: "👠 A Decoy For Murder" }
              ] },
            { href: "/currents/conversations/palladiums-all-time-high", label: "❁ Palladium's All-Time High" },
            { href: "/currents/conversations/fukushimahawaii-update--sun", label: "❁ Fukushima/Hawaii Update ⚛ Sun, May 18, 2014" },
            { href: "/currents/conversations/fukushima-and-diet", label: "❁ Fukushima And Diet" }
          ] }
      ] },
    { href: "/waves", label: "❁ Waves", children: [
        { href: "/waves/radiation-around-the-nation", label: "⚛ Radiation Around The Nation 🌎", children: [
            { href: "/waves/radiation-around-the-nation/your-radiation-69-70-july", label: "⚛ Your Radiation #69/70, July 30 - August 13, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-678--july-16", label: "⚛ Your Radiation #67/8,--July 16-30, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-65-6--july-2", label: "⚛ Your Radiation #65-6,--July 2-16, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-64-july-2-9", label: "⚛ Your Radiation #64, July 2-9, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-62-3-june-18", label: "⚛ Your Radiation #62-3, June 18 - July 2, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-61-june-11", label: "⚛ Your Radiation #61, June 11-18, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-60-june-4-11", label: "⚛ Your Radiation #60, June 4-11, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-59-may-28--", label: "⚛ Your Radiation #59, May 28 - June 4, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-58-may-21-28", label: "⚛ Your Radiation #58, May 21-28, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-57-may-14-21", label: "⚛ Your Radiation #57, May 14-21, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-56-may-7-14", label: "⚛ Your Radiation #56, May 7-14, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-55-apr-30--", label: "⚛ Your Radiation #55, Apr 30 - May 7, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-54-apr-23-30", label: "⚛ Your Radiation #54, Apr 23-30, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-53-apr-16-23", label: "⚛ Your Radiation #53, Apr 16-23, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-52-apr-9-16", label: "⚛ Your Radiation #52, Apr 9-16, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-51-apr-2-9", label: "⚛ Your Radiation #51, Apr 2-9, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-47-50-apr-2-", label: "⚛ Your Radiation #47-50, Mar 5 - Apr 2, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-46-feb-27", label: "⚛ Your Radiation #46, Feb 27-Mar 5, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-45-feb-20-27", label: "⚛ Your Radiation #45, Feb 20-27, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-44-feb-13-20", label: "⚛ Your Radiation #44, Feb 13-20, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-43-feb-6-13", label: "⚛ Your Radiation #43, Feb 6-13, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-42-jan-30--", label: "⚛ Your Radiation #42, Jan 30 - Feb 6, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-41-jan-23-30", label: "⚛ Your Radiation #41, Jan 23-30, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-40-jan-16-23", label: "⚛ Your Radiation #40, Jan 16-23, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-39-jan-9-16", label: "⚛ Your Radiation #39, Jan 9-16, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-38-jan-2-9", label: "⚛ Your Radiation #38, Jan 2-9, 2016 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-37-dec-26--", label: "⚛ Your Radiation #37, Dec 26 - Jan 2, 2015|16 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-36-dec-19-26", label: "⚛ Your Radiation #36, Dec 19-26, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-35-dec-12-19", label: "⚛ Your Radiation #35, Dec 12-19, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-34-dec-5-12", label: "⚛ Your Radiation #34, Dec 5-12, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-33-nov-28--", label: "⚛ Your Radiation #33, Nov 28 - Dec 5, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-32-nov-21-28", label: "⚛ Your Radiation #32, Nov 21-28, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-31-nov-14-21", label: "⚛ Your Radiation #31, Nov 14-21, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-30-nov-7-14", label: "⚛ Your Radiation #30, Nov 7-14, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-29-oct-31--", label: "⚛ Your Radiation #29, Oct 31 - Nov 7, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-28-oct-24-31", label: "⚛ Your Radiation #28, Oct 24-31, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-27-oct-17-24", label: "⚛ Your Radiation #27, Oct 17-24, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-26-oct-10-17", label: "⚛ Your Radiation #26, Oct 10-17, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-25-oct-3-10", label: "⚛ Your Radiation #25, Oct 3-10, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-24-sep-26--", label: "⚛ Your Radiation #24, Sep 26 - Oct 2, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-23-sep-19-26", label: "⚛ Your Radiation #23, Sep 19-26, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-22-sep-12-19", label: "⚛ Your Radiation #22, Sep 12-19, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-21-sep-5-12", label: "⚛ Your Radiation #21, Sep 5-12, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-20-aug-29-", label: "⚛ Your Radiation #20, Aug 29 -Sep 5, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-19-aug-22-29", label: "⚛ Your Radiation #19, Aug 22-29, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-18-aug-15-22", label: "⚛ Your Radiation #18, Aug 15-22, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-17-aug-8", label: "⚛ Your Radiation #17, Aug 8-15, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-august-1-8", label: "⚛ Your Radiation, August 1-8, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-july-24-31", label: "⚛ Your Radiation, July 24-31, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-june-26--", label: "⚛ Your Radiation, June 26 - July 24, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-june-19-26", label: "⚛ Your Radiation, June 19-26, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-june-12-19", label: "⚛ Your Radiation, June 12-19, 2015 🌏" },
            { href: "/waves/radiation-around-the-nation/your-radiation-june-5-12", label: "⚛ Your Radiation, June 5-12, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-may-29--", label: "⚛ Your Radiation, May 29 - June 5, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-may-22-29", label: "⚛ Your Radiation, May 22-29, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-may-15-22", label: "⚛ Your Radiation, May 15-22, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-may-8-15", label: "⚛ Your Radiation, May 8-15, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-may-2-8-2015", label: "⚛ Your Radiation, May 2-8, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-april-24--", label: "⚛ Your Radiation, April 24 - May 1, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-april-17-24", label: "⚛ Your Radiation, April 17-24, 2015 🌎" },
            { href: "/waves/radiation-around-the-nation/your-radiation-april-9-16", label: "⚛ Your Radiation, April 9-16, 2015 🌎" }
          ] },
        { href: "/waves/fire-at-oak-ridge-", label: "🔥 Fire at Oak Ridge 💥" },
        { href: "/waves/nanoweaponry", label: "💥 NANOWEAPONRY 💥", children: [
            { href: "/waves/nanoweaponry/dense-inert-metal-explosive", label: "💥 Dense Inert Metal Explosive 💀" },
            { href: "/waves/nanoweaponry/nanotech-law-of-weaponry", label: "💥 NANOTECH; LAW OF WEAPONRY ☞🔫" }
          ] },
        { href: "/waves/radioactive-cattle-teeth", label: "🐄 Radioactive Cattle Teeth, Fukushima 🏭" },
        { href: "/waves/wikileaks-nsa-and-more", label: "📰 WikiLeaks 🔎 NSA and More 🔦", children: [
            { href: "/waves/wikileaks-nsa-and-more/hillarys-dnc-dossier-", label: "✠ Hillary’s DNC Dossier 🎭" },
            { href: "/waves/wikileaks-nsa-and-more/snowdens-sidtoday-files-", label: "📖 Snowden’s SIDToday Files ✍" },
            { href: "/waves/wikileaks-nsa-and-more/clinton-cybersecurity-fail", label: "❌ Clinton CyberSecurity Fail 🚫" },
            { href: "/waves/wikileaks-nsa-and-more/clintons-designs-on-syria-", label: "⚑ Clinton’s Designs on Syria ➷" },
            { href: "/waves/wikileaks-nsa-and-more/clinton-email-on-syria-", label: "⚑ Clinton eMail on Syria 🎯" }
          ] },
        { href: "/waves/nano-hall-of-mirrors", label: "✨Nano ‘Hall of Mirrors’⚡️" },
        { href: "/waves/into-the-hudson-river", label: "⚛ 💀 ⚛ into the Hudson River 🌎" },
        { href: "/waves/flint-metropolitan-eugenics", label: "🚿 Flint, Metropolitan Eugenics 💀", children: [
            { href: "/waves/flint-metropolitan-eugenics/flint-double-jeopardy-", label: "🚿 Flint, Double Jeopardy 💰" },
            { href: "/waves/flint-metropolitan-eugenics/flint-poison-epidemic-", label: "🚿 Flint, Poison, Epidemic 💉" }
          ] },
        { href: "/waves/existential-threat-nato", label: "🌍 Existential Threat? ☛NATO☚" },
        { href: "/waves/gates-poroshenko-conspiracy", label: "💉 Gates, Poroshenko; Conspiracy, Government 🎯" },
        { href: "/waves/gates-poroshenko-zpg-ukrain", label: "💉 Gates-Poroshenko ZPG Ukraine 💀" },
        { href: "/waves/paris-massacre-perpetrators", label: "💀 Paris Massacre Perpetrators 👤" },
        { href: "/waves/delgado-mind-control", label: "🔪 Delgado, Mind Control ♟" },
        { href: "/waves/most-nuked-nation-on-earth-", label: "🌎 MOST NUKED NATION ON EARTH 🌎" },
        { href: "/waves/radio-frequency-directed", label: "🎯 Radio Frequency Directed Energy 🎯" },
        { href: "/waves/please-dont-pick-the-mutant", label: "⚛ Please, Don’t Pick the Mutants 🌻" },
        { href: "/waves/space-based-weapons-ban", label: "⨳👤⨳ Space-Based Weapons Ban" },
        { href: "/waves/saudi-op-strategy-success", label: "√ Saudi OP Strategy Success" },
        { href: "/waves/gallery-chernobyl-fire", label: "♨️ Gallery ♨️ Chernobyl Fire ♨️ 2015 ♨️" },
        { href: "/waves/monsanto-backdoors-eu", label: "🌍 Monsanto Backdoors E.U." },
        { href: "/waves/crimeas-1st-anniversary", label: "🎉 Crimea’s 1st Anniversary Album 🎉" },
        { href: "/waves/21st-century-eschalon", label: "🌏 21st Century Eschalon" },
        { href: "/waves/international-headline", label: "📰 International Headline Watch 🌏", children: [
            { href: "/waves/international-headline/fort-russ-headlines-", label: "📰 Fort Russ Headlines 🌍" },
            { href: "/waves/international-headline/tass-headlines-", label: "📰 Tass Headlines 🌐" },
            { href: "/waves/international-headline/southfront-headlines-", label: "📰 SouthFront Headlines 🌏" }
          ] },
        { href: "/waves/prouty-place-cut-the-bull", label: "✄ Prouty Place ✑ CUT THE BULL ✂︎", children: [
            { href: "/waves/prouty-place-cut-the-bull/oil-is-renewable-", label: "🌎 Oil is Renewable 🌎" },
            { href: "/waves/prouty-place-cut-the-bull/that-whole-bay-of-pigs", label: "👥 That Whole Bay Of Pigs Thing" },
            { href: "/waves/prouty-place-cut-the-bull/lansdale-at-the-kennedy", label: "☛ Lansdale at the Kennedy Assassination ⚑" }
          ] },
        { href: "/waves/how-to-wreck-the-environmen", label: "🌏 How To Wreck The Environment" },
        { href: "/waves/plutonium-isotopes-off", label: "🇯🇵 Plutonium Isotopes Off Japan" },
        { href: "/waves/depopulation-agenda-europe-", label: "🌍 Depopulation Agenda: Europe 👤" },
        { href: "/waves/cease-covert-depopulation", label: "🔪💉Cease Covert Depopulation Letter🔪💉" },
        { href: "/waves/dutch-apologize-for-mh-17", label: "❁ Dutch Apologize for MH-17 Lies" },
        { href: "/waves/pacific-dead-from-fukushima", label: "❁ Pacific Dead from Fukushima" },
        { href: "/waves/strange-fish-story", label: "❁ Strange Fish Story" },
        { href: "/waves/blood-composition-of-monkey", label: "❁ Blood Composition of Monkeys Altered Near Fukushima" },
        { href: "/waves/secret-army-bases", label: "❁ Secret Army Bases" },
        { href: "/waves/fukushima-plutonium-effect", label: "⚛ Fukushima Plutonium Effect ⚛", children: [
            { href: "/waves/fukushima-plutonium-effect/20130423-_poster--estimatio", label: "20130423 _Poster- Estimation of Nuclear-Energy Excursion Possibility during Fukushima-1 NPP Accident-poster session, T2-P22" },
            { href: "/waves/fukushima-plutonium-effect/fukushima-blow-up-regimes", label: "⚛ Fukushima Blow-Up Regimes ⚛" }
          ] },
        { href: "/waves/rand-demographic-military", label: "➷ RAND Demographic Military Power ➷" },
        { href: "/waves/depleted-uranium--dna-damag", label: "⚛ Depleted Uranium | DNA Damage ⚛" },
        { href: "/waves/hidden-genocide-by-dr-ernes", label: "❁ Hidden Genocide: by Dr. Ernest Sternglass" },
        { href: "/waves/space-preservation-act-of", label: "❁ Space Preservation Act of 2001" },
        { href: "/waves/1972-rothschild-ball", label: "❁ 1972 Rothschild Ball" },
        { href: "/waves/unsafe-radwaste-disposal", label: "❁ Unsafe Radwaste Disposal" },
        { href: "/waves/fallout-and-reproduction-of", label: "♆ Fallout and Reproduction of Ocean Fish Populations" }
      ] },
    { href: "/lifestyle", label: "❁ Lifestyle", children: [
        { href: "/lifestyle/lmgnc-bookshelf", label: "📖 LM:GNC BookShelf", children: [
            { href: "/lifestyle/lmgnc-bookshelf/manuscripts-", label: "✑ Manuscripts ✍" },
            { href: "/lifestyle/lmgnc-bookshelf/1984-george-orwell-", label: "🔴 “1984” George Orwell 💀" },
            { href: "/lifestyle/lmgnc-bookshelf/the-nameless-war-", label: "➷ THE NAMELESS WAR 💣" },
            { href: "/lifestyle/lmgnc-bookshelf/who-owns-the-world", label: "🌍 Who Owns the World" },
            { href: "/lifestyle/lmgnc-bookshelf/order-of-skull--bones", label: "💀 Order OF Skull & Bones" },
            { href: "/lifestyle/lmgnc-bookshelf/angels-dont-play-this-haarp", label: "🎼 Angels Don't Play this HAARP" },
            { href: "/lifestyle/lmgnc-bookshelf/genocide-in-iraq-viii", label: "👥 Genocide In Iraq v.I&II" },
            { href: "/lifestyle/lmgnc-bookshelf/double-life-of-fidel-castro", label: "♟ Double Life of Fidel Castro ♚" }
          ] },
        { href: "/lifestyle/the-ancient-ghost-city-of", label: "❁ The Ancient Ghost City of Ani" }
      ] },
    { href: "/archive", label: "❁ Archive", children: [
        { href: "/archive/nanoparticle-toxicity-w-leuren", label: "📻 Nanoparticle Toxicity with Leuren Moret ❦" },
        { href: "/archive/new-bombs-and-war-crimes-in", label: "❁ New Bombs and War Crimes in Fallujah" },
        { href: "/archive/global-climate-change---", label: "❁ Global Climate Change . . ." },
        { href: "/archive/international-radiation", label: "⚛ International Radiation Distribution ⚛", children: [
            { href: "/archive/international-radiation/radiation-poisons-generatio", label: "Radiation Poisons Generations" },
            { href: "/archive/international-radiation/sellafield--global-dose", label: "Sellafield | Global Dose Test" }
          ] },
        { href: "/archive/depleted-uraniumndna-", label: "💀 Depleted Uranium’n’DNA 😱" },
        { href: "/archive/uc-regents-lose-nuke-pgm", label: "❁ UC Regents Lose Nuke Pgm" },
        { href: "/archive/du-trojan-horse", label: "❁ DU-Trojan Horse" },
        { href: "/archive/lmgnc-pt1", label: "❁ LM:GNC (Pt1)" },
        { href: "/archive/lmgnc-pt2", label: "❁ LM:GNC (Pt2)" },
        { href: "/archive/world-uranium-weapons-confe", label: "❁ World Uranium Weapons Conference 2003" },
        { href: "/archive/radionuclide-remobilization", label: "⚛ Radionuclide ReMobilization Abatement" },
        { href: "/archive/america-first-transcription", label: "❁ \"America First\" Transcription" },
        { href: "/archive/whale-archive-transcription", label: "❁ \"Whale Archive\" Transcription" }
      ] },
    { href: "/glossary", label: "❁ Glossary" },
    { href: "/contact", label: "❁ Contact" }
  ]
